@EvaluateItEasily.API_HostAddress = http://localhost:5208

GET {{EvaluateItEasily.API_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{EvaluateItEasily.API_HostAddress}}/api/Files/presigned-upload?fileName=test.pdf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjQ1NDc4Ny01MmJjLTQwZjYtOTAwNy0yZDUxMzgwOWJmNzUiLCJlbWFpbCI6InJhenpha0BnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoicmF6emFrIiwianRpIjoiZGUyOWM1NmEtNTVjMC00MTQ1LWFmZWYtOTkzYzdiMTlhYjQ0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsImV4cCI6MTc3NzIwODA0OSwiaXNzIjoiRXZhbHVhdGVJdEVhc2lseSIsImF1ZCI6IlJlYWN0QXBwIn0.UpuB_QrkPcfpfenxY8y6q-4zy2rQsF-2CP0ZDBnd6go
Accept: application/json 